import { Verb } from './stores/verbs'
import { shuffle } from 'lodash'

const sourceVerbs: Verb[] = [
  {
    "v1": "dig",
    "v2": "dug",
    "v3": "dug",
    "translate": "копать, рыть",
    "score": 0,
  },
  {
    "v1": "know",
    "v2": "knew",
    "v3": "known",
    "translate": "знать, иметь представление",
    "score": 0,
  },
  {
    "v1": "sweep",
    "v2": "swept",
    "v3": "swept",
    "translate": "мести, подметать, смахивать",
    "score": 0,
  },
  {
    "v1": "mean",
    "v2": "meant",
    "v3": "meant",
    "translate": "значить, иметь в виду, подразумевать",
    "score": 0,
  },
  {
    "v1": "do",
    "v2": "did",
    "v3": "done",
    "translate": "делать, выполнять",
    "score": 0,
  },
  {
    "v1": "forget",
    "v2": "forgot",
    "v3": "forgotten",
    "translate": "забывать о (чём-либо)",
    "score": 0,
  },
  {
    "v1": "ring",
    "v2": "rang",
    "v3": "rung",
    "translate": "звенеть, звонить",
    "score": 0,
  },
  {
    "v1": "break",
    "v2": "broke",
    "v3": "broken",
    "translate": "ломать, разбивать, разрушать",
    "score": 0,
  },
  {
    "v1": "be",
    "v2": "was, were",
    "v3": "been",
    "translate": "быть, являться",
    "score": 0,
  },
  {
    "v1": "fly",
    "v2": "flew",
    "v3": "flown",
    "translate": "летать",
    "score": 0,
  },
  {
    "v1": "tell",
    "v2": "told",
    "v3": "told",
    "translate": "рассказывать",
    "score": 0,
  },
  {
    "v1": "build",
    "v2": "built",
    "v3": "built",
    "translate": "строить, сооружать",
    "score": 0,
  },
  {
    "v1": "stick",
    "v2": "stuck",
    "v3": "stuck",
    "translate": "втыкать, приклеивать",
    "score": 0,
  },
  {
    "v1": "cost",
    "v2": "cost",
    "v3": "cost",
    "translate": "стоить, обходиться",
    "score": 0,
  },
  {
    "v1": "have",
    "v2": "had",
    "v3": "had",
    "translate": "иметь, обладать",
    "score": 0,
  },
  {
    "v1": "take",
    "v2": "took",
    "v3": "taken",
    "translate": "брать, хватать, взять",
    "score": 0,
  },
  {
    "v1": "sell",
    "v2": "sold",
    "v3": "sold",
    "translate": "продавать, торговать",
    "score": 0,
  },
  {
    "v1": "shoot",
    "v2": "shot",
    "v3": "shot",
    "translate": "стрелять",
    "score": 0,
  },
  {
    "v1": "sink",
    "v2": "sank",
    "v3": "sunk",
    "translate": "тонуть, погружаться",
    "score": 0,
  },
  {
    "v1": "hear",
    "v2": "heard",
    "v3": "heard",
    "translate": "слышать, услышать",
    "score": 0,
  },
  {
    "v1": "write",
    "v2": "wrote",
    "v3": "written",
    "translate": "писать, записывать",
    "score": 0,
  },
  {
    "v1": "swear",
    "v2": "swore",
    "v3": "sworn",
    "translate": "клясться, присягать",
    "score": 0,
  },
  {
    "v1": "choose",
    "v2": "chose",
    "v3": "chosen",
    "translate": "выбирать, избирать",
    "score": 0,
  },
  {
    "v1": "deal",
    "v2": "dealt",
    "v3": "dealt",
    "translate": "иметь дело, распределять",
    "score": 0,
  },
  {
    "v1": "drink",
    "v2": "drank",
    "v3": "drunk",
    "translate": "пить",
    "score": 0,
  },
  {
    "v1": "give",
    "v2": "gave",
    "v3": "given",
    "translate": "дать, подать, дарить",
    "score": 0,
  },
  {
    "v1": "let",
    "v2": "let",
    "v3": "let",
    "translate": "позволять, разрешать",
    "score": 0,
  },
  {
    "v1": "lend",
    "v2": "lent",
    "v3": "lent",
    "translate": "одалживать, давать взаймы (в долг)",
    "score": 0,
  },
  {
    "v1": "think",
    "v2": "thought",
    "v3": "thought",
    "translate": "думать, мыслить, размышлять",
    "score": 0,
  },
  {
    "v1": "shine",
    "v2": "shone",
    "v3": "shone",
    "translate": "светить, сиять, озарять",
    "score": 0,
  },
  {
    "v1": "see",
    "v2": "saw",
    "v3": "seen",
    "translate": "видеть",
    "score": 0,
  },
  {
    "v1": "come",
    "v2": "came",
    "v3": "come",
    "translate": "приходить, подходить",
    "score": 0,
  },
  {
    "v1": "wake",
    "v2": "woke",
    "v3": "woken",
    "translate": "просыпаться, будить",
    "score": 0,
  },
  {
    "v1": "tear",
    "v2": "tore",
    "v3": "torn",
    "translate": "рвать, отрывать",
    "score": 0,
  },
  {
    "v1": "make",
    "v2": "made",
    "v3": "made",
    "translate": "делать, создавать, изготавливать",
    "score": 0,
  },
  {
    "v1": "get",
    "v2": "got",
    "v3": "got",
    "translate": "получать, добираться",
    "score": 0,
  },
  {
    "v1": "fight",
    "v2": "fought",
    "v3": "fought",
    "translate": "драться, сражаться, воевать",
    "score": 0,
  },
  {
    "v1": "swim",
    "v2": "swam",
    "v3": "swum",
    "translate": "плавать, плыть",
    "score": 0,
  },
  {
    "v1": "stand",
    "v2": "stood",
    "v3": "stood",
    "translate": "стоять",
    "score": 0,
  },
  {
    "v1": "wear",
    "v2": "wore",
    "v3": "worn",
    "translate": "носить (одежду)",
    "score": 0,
  },
  {
    "v1": "meet",
    "v2": "met",
    "v3": "met",
    "translate": "встречать, знакомиться",
    "score": 0,
  },
  {
    "v1": "beat",
    "v2": "beat",
    "v3": "beaten",
    "translate": "бить, колотить",
    "score": 0,
  },
  {
    "v1": "throw",
    "v2": "threw",
    "v3": "thrown",
    "translate": "бросать, кидать, метать",
    "score": 0,
  },
  {
    "v1": "rise",
    "v2": "rose",
    "v3": "risen",
    "translate": "восходить, вставать, подниматься",
    "score": 0,
  },
  {
    "v1": "ride",
    "v2": "rode",
    "v3": "ridden",
    "translate": "ехать верхом, кататься",
    "score": 0,
  },
  {
    "v1": "bite",
    "v2": "bit",
    "v3": "bitten",
    "translate": "кусать",
    "score": 0,
  },
  {
    "v1": "spend",
    "v2": "spent",
    "v3": "spent",
    "translate": "тратить, расходовать, проводить (время)",
    "score": 0,
  },
  {
    "v1": "freeze",
    "v2": "froze",
    "v3": "frozen",
    "translate": "замерзать, замирать",
    "score": 0,
  },
  {
    "v1": "feel",
    "v2": "felt",
    "v3": "felt",
    "translate": "чувствовать, ощущать",
    "score": 0,
  },
  {
    "v1": "seek",
    "v2": "sought",
    "v3": "sought",
    "translate": "искать, разыскивать",
    "score": 0,
  },
  {
    "v1": "eat",
    "v2": "ate",
    "v3": "eaten",
    "translate": "есть, поглощать, поедать",
    "score": 0,
  },
  {
    "v1": "lose",
    "v2": "lost",
    "v3": "lost",
    "translate": "терять, лишаться, утрачивать",
    "score": 0,
  },
  {
    "v1": "leave",
    "v2": "left",
    "v3": "left",
    "translate": "покидать, уходить, уезжать, оставлять",
    "score": 0,
  },
  {
    "v1": "blow",
    "v2": "blew",
    "v3": "blown",
    "translate": "дуть, выдыхать",
    "score": 0,
  },
  {
    "v1": "fall",
    "v2": "fell",
    "v3": "fallen",
    "translate": "падать",
    "score": 0,
  },
  {
    "v1": "understand",
    "v2": "understood",
    "v3": "understood",
    "translate": "понимать, постигать",
    "score": 0,
  },
  {
    "v1": "lie",
    "v2": "lay",
    "v3": "lain",
    "translate": "лежать",
    "score": 0,
  },
  {
    "v1": "begin",
    "v2": "began",
    "v3": "begun",
    "translate": "начинать",
    "score": 0,
  },
  {
    "v1": "draw",
    "v2": "drew",
    "v3": "drawn",
    "translate": "рисовать, чертить",
    "score": 0,
  },
  {
    "v1": "strike",
    "v2": "struck",
    "v3": "struck, stricken",
    "translate": "ударять, бить, поражать",
    "score": 0,
  },
  {
    "v1": "hide",
    "v2": "hid",
    "v3": "hidden",
    "translate": "прятать, скрывать",
    "score": 0,
  },
  {
    "v1": "lead",
    "v2": "led",
    "v3": "led",
    "translate": "вести за собой, сопровождать, руководить",
    "score": 0,
  },
  {
    "v1": "become",
    "v2": "became",
    "v3": "become",
    "translate": "становиться",
    "score": 0,
  },
  {
    "v1": "sit",
    "v2": "sat",
    "v3": "sat",
    "translate": "сидеть, садиться",
    "score": 0,
  },
  {
    "v1": "cut",
    "v2": "cut",
    "v3": "cut",
    "translate": "резать, разрезать",
    "score": 0,
  },
  {
    "v1": "pay",
    "v2": "paid",
    "v3": "paid",
    "translate": "платить, оплачивать, рассчитываться",
    "score": 0,
  },
  {
    "v1": "read",
    "v2": "read",
    "v3": "read",
    "translate": "читать, прочитать",
    "score": 0,
  },
  {
    "v1": "buy",
    "v2": "bought",
    "v3": "bought",
    "translate": "покупать, приобретать",
    "score": 0,
  },
  {
    "v1": "bring",
    "v2": "brought",
    "v3": "brought",
    "translate": "приносить, привозить, доставлять",
    "score": 0,
  },
  {
    "v1": "go",
    "v2": "went",
    "v3": "gone",
    "translate": "идти, двигаться",
    "score": 0,
  },
  {
    "v1": "say",
    "v2": "said",
    "v3": "said",
    "translate": "говорить, сказать, произносить",
    "score": 0,
  },
  {
    "v1": "shake",
    "v2": "shook",
    "v3": "shaken",
    "translate": "трясти, встряхивать",
    "score": 0,
  },
  {
    "v1": "run",
    "v2": "ran",
    "v3": "run",
    "translate": "бежать, бегать",
    "score": 0,
  },
  {
    "v1": "hurt",
    "v2": "hurt",
    "v3": "hurt",
    "translate": "ранить, причинять боль, ушибить",
    "score": 0,
  },
  {
    "v1": "swing",
    "v2": "swung",
    "v3": "swung",
    "translate": "качаться, вертеться",
    "score": 0,
  },
  {
    "v1": "keep",
    "v2": "kept",
    "v3": "kept",
    "translate": "хранить, сохранять, поддерживать",
    "score": 0,
  },
  {
    "v1": "bend",
    "v2": "bent",
    "v3": "bent",
    "translate": "гнуть",
    "score": 0,
  },
  {
    "v1": "find",
    "v2": "found",
    "v3": "found",
    "translate": "находить, обнаруживать",
    "score": 0,
  },
  {
    "v1": "sing",
    "v2": "sang",
    "v3": "sung",
    "translate": "петь, напевать",
    "score": 0,
  },
  {
    "v1": "bet",
    "v2": "bet",
    "v3": "bet",
    "translate": "держать пари",
    "score": 0,
  },
  {
    "v1": "teach",
    "v2": "taught",
    "v3": "taught",
    "translate": "учить, обучать",
    "score": 0,
  },
  {
    "v1": "lay",
    "v2": "laid",
    "v3": "laid",
    "translate": "класть, положить, покрывать",
    "score": 0,
  },
  {
    "v1": "light",
    "v2": "lit",
    "v3": "lit",
    "translate": "зажигать, светиться, освещать",
    "score": 0,
  },
  {
    "v1": "grow",
    "v2": "grew",
    "v3": "grown",
    "translate": "расти, вырастать",
    "score": 0,
  },
  {
    "v1": "catch",
    "v2": "caught",
    "v3": "caught",
    "translate": "ловить, поймать, схватить",
    "score": 0,
  },
  {
    "v1": "send",
    "v2": "sent",
    "v3": "sent",
    "translate": "посылать, отправлять, отсылать",
    "score": 0,
  },
  {
    "v1": "hold",
    "v2": "held",
    "v3": "held",
    "translate": "держать, удерживать, задерживать",
    "score": 0,
  },
  {
    "v1": "set",
    "v2": "set",
    "v3": "set",
    "translate": "устанавливать, задавать, назначать",
    "score": 0,
  },
  {
    "v1": "feed",
    "v2": "fed",
    "v3": "fed",
    "translate": "кормить",
    "score": 0,
  },
  {
    "v1": "hit",
    "v2": "hit",
    "v3": "hit",
    "translate": "ударять, поражать",
    "score": 0,
  },
  {
    "v1": "sleep",
    "v2": "slept",
    "v3": "slept",
    "translate": "спать",
    "score": 0,
  },
  {
    "v1": "show",
    "v2": "showed",
    "v3": "shown, showed",
    "translate": "показывать",
    "score": 0,
  },
  {
    "v1": "shut",
    "v2": "shut",
    "v3": "shut",
    "translate": "закрывать, запирать, затворять",
    "score": 0,
  },
  {
    "v1": "steal",
    "v2": "stole",
    "v3": "stolen",
    "translate": "воровать, красть",
    "score": 0,
  },
  {
    "v1": "hang",
    "v2": "hung",
    "v3": "hung",
    "translate": "вешать, развешивать, висеть",
    "score": 0,
  },
  {
    "v1": "win",
    "v2": "won",
    "v3": "won",
    "translate": "победить, выиграть",
    "score": 0,
  },
  {
    "v1": "speak",
    "v2": "spoke",
    "v3": "spoken",
    "translate": "говорить, разговаривать, высказываться",
    "score": 0,
  },
  {
    "v1": "forgive",
    "v2": "forgave",
    "v3": "forgiven",
    "translate": "прощать",
    "score": 0,
  },
  {
    "v1": "drive",
    "v2": "drove",
    "v3": "driven",
    "translate": "ездить, подвозить",
    "score": 0,
  },
  {
    "v1": "put",
    "v2": "put",
    "v3": "put",
    "translate": "ставить, помещать, класть",
    "score": 0,
  }
]

export default shuffle(sourceVerbs)